server:
  port: ${PORT:80}
  servlet:
    context-path: /
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
management:
  tracing:
    sampling:
      probability: 1
rest:
  ms-auth:
    name: ms-auth
    path: /auth
    rewrite-path: /ms-auth
  ms-client:
    name: ms-client
    path: /client
    rewrite-path: /ms-client
